name: lwsspy
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.7
  - ipython
  - flake
  - pytest
  - matplotlib
  - numpy
  - mypy
  - scipy
  - cartopy
  - mpi4py
  - jupyterlab
  - pyvista
  - pip
  - pip:
    - obspy
    - xarray
    - beautifulsoup4
    - pyasdf
    - pyyaml
    - sphinx
    - pydata_sphinx_theme
    - sphinx_copybutton
    - git+git://github.com/wjlei1990/pyflex.git@merge